# NumPy
NumPy 对象是一个 **同类型** 多维数组（ndarray），其维度称为 **轴（axes）** ，每轴有多少个元素称为 **该轴的长度** 为多少。
- **ndarray.ndim：** 轴数。
- **ndarray.shape：** 一个元组，表示 ndarray 在每个轴上的长度。
- **ndarray.size：** 该 ndarray 里总共有多少个元素，等于 shape 中所有轴长度的乘积。
- **ndarray.dtype：** 一个 ndarray 的所有元素必须是同类型的，可以指定标准 Python 类型或 NumPy 自己的类型。

In [3]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"
import numpy as np

### 一、ndarray 的创建

#### 1. 将 Python 序列转换为 NumPy ndarray

In [28]:
array1d = np.array([1, 2, 3, 4])
print(array1d)
print("Shape:", array1d.shape, "\n")

array2d = np.array([[1, 2], [3, 4]])
print(array2d)
print("Shape:", array2d.shape, "\n")

array3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(array3d)
print("Shape:", array3d.shape, "\n")

[1 2 3 4]
Shape: (4,) 

[[1 2]
 [3 4]]
Shape: (2, 2) 

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2) 



In [ ]:
np.array([[1, 2], [3, 4]], dtype=complex)  # array 类型可以在创建期间明确指定

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

#### 2. 使用 NumPy ndarray 创建函数

##### 一维 ndarray 创建函数

In [68]:
start, stop, step = 2, 10, 0.1

np.arange(stop)
np.arange(start, stop)
np.arange(start, stop, step)  # 类似于 Python range()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([2, 3, 4, 5, 6, 7, 8, 9])

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2,
       3.3, 3.4, 3.5, 3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5,
       4.6, 4.7, 4.8, 4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8,
       5.9, 6. , 6.1, 6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1,
       7.2, 7.3, 7.4, 7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4,
       8.5, 8.6, 8.7, 8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7,
       9.8, 9.9])

In [ ]:
start, stop, count = 1, 4, 6

np.linspace(start, stop, count)  # 在指定的起始值和结束值之间等距分布，最终元素数量为 count

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

In [ ]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

np.diag(a)  # 当 np.diag() 作用于二维 ndarray 时， 返回其对角线上的值作为一个一维 ndarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([1, 5, 9])

##### 二维 ndarray 创建函数

In [20]:
np.eye(3)
np.eye(3, 5)  # 行索引和列索引相等的位置为1， 其余为0

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [ ]:
np.diag([1,2,3])  # 当 np.diag() 作用于一维 ndarray 时，返回沿对角线具有给定值的方形二维 ndarray

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

##### 通用n维 ndarray 创建函数

In [10]:
np.zeros((3,4))  # 按形状创建一个全0的ndarray

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
np.ones((3,4))  # 按形状创建一个全1的ndarray

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [12]:
np.empty((3,4))  # 按形状创建一个ndarray，不对数值做初始化（提高速度），其内容取决于内存状态

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.random.random((3,4))  # 按形状创建一个填充(0,1)随机数的ndarray

array([[0.39901419, 0.15543947, 0.09395769, 0.37918101],
       [0.56049969, 0.01665194, 0.40070915, 0.75820648],
       [0.28309414, 0.52280029, 0.52519451, 0.61502749]])

### 二、ndarray 的基本运算
对于不同类型的 ndarray 进行运算时，类型会向上转换（upcasting）

In [ ]:
a = np.array([[20, 30, 40, 50], [60, 70, 80, 90]])
b = 4
c = np.arange(8).reshape(2, 4)
c

a + b  # 加/减一个标量（广播机制）
a - c  # 加/减一个相同形状的 ndarray （逐元素应用）
c ** 2
c // 2 
np.sin(a)  # 通过 NumPy 通用函数计算
a < 45  # 逻辑运算

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

array([[24, 34, 44, 54],
       [64, 74, 84, 94]])

array([[20, 29, 38, 47],
       [56, 65, 74, 83]])

array([[ 0,  1,  4,  9],
       [16, 25, 36, 49]])

array([[0, 0, 1, 1],
       [2, 2, 3, 3]])

array([[ 0.91294525, -0.98803162,  0.74511316, -0.26237485],
       [-0.30481062,  0.77389068, -0.99388865,  0.89399666]])

array([[ True,  True,  True, False],
       [False, False, False, False]])

In [7]:
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])

A * B  # 逐元素相乘
A.dot(B)  # 矩阵乘法
A @ B  # 矩阵乘法（Python >=3.5）

array([[2, 0],
       [0, 4]])

array([[5, 4],
       [3, 4]])

array([[5, 4],
       [3, 4]])

In [13]:
# 一些常见的数学函数
a = np.arange(3)
a

np.sin(a)
np.cos(a)
np.exp(a)

array([0, 1, 2])

array([0.        , 0.84147098, 0.90929743])

array([ 1.        ,  0.54030231, -0.41614684])

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
a = np.arange(12).reshape(3, 4)
a
# 不指定参数时，对整个 ndarray 来求
a.sum()
a.min()
a.max()
a.mean()

# 指定 axis 时，会对指定的轴来求
a.sum(axis=0)
a.min(axis=1)
a.cumsum(axis=1)  # 每行累计和

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

np.int64(66)

np.int64(0)

np.int64(11)

np.float64(5.5)

array([12, 15, 18, 21])

array([0, 4, 8])

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [49]:
# 矩阵的排序
a = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(a)

array([1, 2, 3, 4, 5, 6, 7, 8])

### 三、ndarray 的索引、切片和迭代
> 注意：在 Python中，x[(1, 2, 3, ..., n)] 等同于 x[1, 2, 3, ..., n]，后者只是前者的语法糖。
#### 1. 基本索引
##### 单元素索引

In [17]:
# 一维 ndarray 索引方式和 Python 其他序列类型一致
x = np.arange(10)
x
x[2]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

np.int64(2)

In [18]:
# 多维 ndarray 每个轴都可以有一个索引
x = np.arange(24).reshape(2, 3, 4)
x
x[1, 2, 3]

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

np.int64(23)

In [19]:
# 若对多维 ndarray 进行索引，但给出的索引数少于维数时，会得到子维 ndarray
x[1, 2]
x[1]

array([20, 21, 22, 23])

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

##### 切片索引
当每个轴给出的是切片对象（形如 start:stop:step 的符号构造），就会由索引单个值变成切片。
> 注意：NumPy切片总是创建一个 view，而不是像 Python 序列那样创建副本。

In [ ]:
a = np.arange(120).reshape(4,5,6)
a

a[:2,:3,:4]  # 每个轴都可以应用切片对象
a[:2,:3]  # 当给出的切片对象数量少于轴数时，相当于剩余的轴不应用切片
a[2,:3,:4]  # 可以混用单值索引和切片对象
a[..., :4]  # 等同于a[:,:,:4]

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

array([[[ 0,  1,  2,  3],
        [ 6,  7,  8,  9],
        [12, 13, 14, 15]],

       [[30, 31, 32, 33],
        [36, 37, 38, 39],
        [42, 43, 44, 45]]])

array([[[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11],
        [12, 13, 14, 15, 16, 17]],

       [[30, 31, 32, 33, 34, 35],
        [36, 37, 38, 39, 40, 41],
        [42, 43, 44, 45, 46, 47]]])

array([[60, 61, 62, 63],
       [66, 67, 68, 69],
       [72, 73, 74, 75]])

array([[[  0,   1,   2,   3],
        [  6,   7,   8,   9],
        [ 12,  13,  14,  15],
        [ 18,  19,  20,  21],
        [ 24,  25,  26,  27]],

       [[ 30,  31,  32,  33],
        [ 36,  37,  38,  39],
        [ 42,  43,  44,  45],
        [ 48,  49,  50,  51],
        [ 54,  55,  56,  57]],

       [[ 60,  61,  62,  63],
        [ 66,  67,  68,  69],
        [ 72,  73,  74,  75],
        [ 78,  79,  80,  81],
        [ 84,  85,  86,  87]],

       [[ 90,  91,  92,  93],
        [ 96,  97,  98,  99],
        [102, 103, 104, 105],
        [108, 109, 110, 111],
        [114, 115, 116, 117]]])

#### 2. 高级索引
当[]中至少包括非元组Python序列（因为元组会被认为是单元素索引， x[(1, 2, 3),] 与 x[(1, 2, 3)] 有根本区别。后者相当于 x[1, 2, 3] ，会触发基本选择，而前者会触发高级索引）或为整型/布尔型的ndarray时，会触发高级索引。
> 注意：高级索引总是创建一份数据的 copy
##### 整数数组索引

In [69]:
a = np.arange(120).reshape(4,5,6)
a

# 整数数组索引允许根据 N 维索引选择 ndarray 中的任意项。每个整数数组代表该维度的要选取哪些位置的对象，允许使用负数
a[[1,3]]
a[[1,3],[1,3]]

array([[[  0,   1,   2,   3,   4,   5],
        [  6,   7,   8,   9,  10,  11],
        [ 12,  13,  14,  15,  16,  17],
        [ 18,  19,  20,  21,  22,  23],
        [ 24,  25,  26,  27,  28,  29]],

       [[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 60,  61,  62,  63,  64,  65],
        [ 66,  67,  68,  69,  70,  71],
        [ 72,  73,  74,  75,  76,  77],
        [ 78,  79,  80,  81,  82,  83],
        [ 84,  85,  86,  87,  88,  89]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

array([[[ 30,  31,  32,  33,  34,  35],
        [ 36,  37,  38,  39,  40,  41],
        [ 42,  43,  44,  45,  46,  47],
        [ 48,  49,  50,  51,  52,  53],
        [ 54,  55,  56,  57,  58,  59]],

       [[ 90,  91,  92,  93,  94,  95],
        [ 96,  97,  98,  99, 100, 101],
        [102, 103, 104, 105, 106, 107],
        [108, 109, 110, 111, 112, 113],
        [114, 115, 116, 117, 118, 119]]])

array([[ 36,  37,  38,  39,  40,  41],
       [108, 109, 110, 111, 112, 113]])

##### 布尔数组索引
常用于过滤符合条件的元素

In [9]:
# 例：从 ndarray 中选出所有不为nan的项目
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x
~np.isnan(x)
x[~np.isnan(x)]

array([[ 1.,  2.],
       [nan,  3.],
       [nan, nan]])

array([[ True,  True],
       [False,  True],
       [False, False]])

array([1., 2., 3.])

In [10]:
# 例：给所有负元素添加一个常数
x = np.array([1., -1., -2., 3])
x
x < 0
x[x < 0] += 20
x

array([ 1., -1., -2.,  3.])

array([False,  True,  True, False])

array([ 1., 19., 18.,  3.])

In [56]:
# 应用：获取满足条件的元素的索引——用np.nonzero获取布尔数组中不为False的元素的索引
a = np.arange(12).reshape(3,4)
a

x = np.nonzero(a < 5)
x
list(zip(x[0], x[1]))  # 获取坐标

a[x]  # 可以直接用这些索引提取出对应的元素

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

(array([0, 0, 0, 0, 1], dtype=int64), array([0, 1, 2, 3, 0], dtype=int64))

[(0, 0), (0, 1), (0, 2), (0, 3), (1, 0)]

array([0, 1, 2, 3, 4])

#### 3. 迭代

In [11]:
# 一维 ndarray 的迭代如同 Python 序列一样
a = np.arange(10)
for _ in a:
    print(_)

0
1
2
3
4
5
6
7
8
9


In [13]:
# 多维 ndarray 的迭代是针对第一个轴进行的
a = np.arange(40).reshape(5,4,2)
a
for _ in a:
    print(_)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11],
        [12, 13],
        [14, 15]],

       [[16, 17],
        [18, 19],
        [20, 21],
        [22, 23]],

       [[24, 25],
        [26, 27],
        [28, 29],
        [30, 31]],

       [[32, 33],
        [34, 35],
        [36, 37],
        [38, 39]]])

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
[[ 8  9]
 [10 11]
 [12 13]
 [14 15]]
[[16 17]
 [18 19]
 [20 21]
 [22 23]]
[[24 25]
 [26 27]
 [28 29]
 [30 31]]
[[32 33]
 [34 35]
 [36 37]
 [38 39]]


In [14]:
# 若想遍历 ndarray 的每一个元素，则用.flat属性调用 ndarray 所有元素的迭代器
for _ in a.flat:
    print(_)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39


### 四、形状操作
#### 1. 重塑 ndarray 的形状

In [65]:
# 以下的命令返回修改后的 ndarray，但不更改原始的 ndarray
a = np.arange(20).reshape(4,5)
a
a.shape

a.ravel()  # 1.展平数组
a.reshape(2,2,5)  # 2.改变形状
a.reshape(2,-1,5)  # reshape 可以自动推断剩下一个为-1的轴的长度
a.T  # 3.转置

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

(4, 5)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [66]:
# 以下命令修改 ndarray 自身
a.resize(2,2,5)
a

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [67]:
# ravel()和flatten()都用于展平，但ravel生成一个view，而flatten生成一个copy
b = a.ravel()
b.base is a.base
c = a.flatten()
c.base is a.base

True

False

#### 2. 向 ndarray 添加新轴

In [51]:
a = np.arange(7)
a
a.shape

# 通过 np.newaxis 利用切片方式在指定位置添加新轴
b = a[np.newaxis, :]
b
b.shape

b = a[np.newaxis, :, np.newaxis]
b
b.shape


array([0, 1, 2, 3, 4, 5, 6])

(7,)

array([[0, 1, 2, 3, 4, 5, 6]])

(1, 7)

array([[[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6]]])

(1, 7, 1)

In [52]:
# 通过 np.expand_dims 在指定位置添加新轴
c = np.expand_dims(a, axis=0)
c
c.shape

array([[0, 1, 2, 3, 4, 5, 6]])

(1, 7)

#### 2. 将不同的 ndarray 堆叠在一起

In [48]:
a = np.arange(1,5).reshape(2,2)
a
b = np.arange(5,9).reshape(2,2)
b

# 需要传入一个元组
np.vstack((a,b))  # 纵向堆叠/沿第1个轴堆叠
np.hstack((a,b))  # 横向堆叠/沿第2个轴堆叠
np.concatenate((a,b), axis=0)  # 指定按第几轴堆叠


array([[1, 2],
       [3, 4]])

array([[5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

#### 3. 将一个 ndarray 拆分成数个小 ndarray

In [30]:
a = np.arange(24).reshape(2,12)
a

np.hsplit(a, 3)  # 将a横向拆分成3个相同形状的ndarray
np.hsplit(a, (3,5))  # 将a在第3列和第5列处断开
np.vsplit(a, 2)  # 将a纵向拆分成2个相同形状的ndarray
np.array_split(a, 2, axis=0)  # 将a沿第0轴拆分成2个相同形状的ndarray

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])

[array([[ 0,  1,  2,  3],
        [12, 13, 14, 15]]), array([[ 4,  5,  6,  7],
        [16, 17, 18, 19]]), array([[ 8,  9, 10, 11],
        [20, 21, 22, 23]])]

[array([[ 0,  1,  2],
        [12, 13, 14]]), array([[ 3,  4],
        [15, 16]]), array([[ 5,  6,  7,  8,  9, 10, 11],
        [17, 18, 19, 20, 21, 22, 23]])]

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])]

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]])]

### 五、视图（view）和副本（copy）
#### 1. 视图

In [41]:
# 单纯的赋值是由 Python 将可变对象作为引用传递，两个变量名指向同一对象
a = np.arange(12).reshape(3,4)

b = a
b is a

True

In [42]:
# 视图是一个新对象，但指向相同的 NumPy 数据。不同的ndarray对象可以共享相同的数据
c = a.view()
c

c is a
c.base is a.base
c.flags.owndata

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

False

True

False

In [43]:
c = c.reshape(2,6)  # 对视图c做的形状变化不会传递给a
c.shape
a.shape

c[0, 4] = 1234  # 但元素值的变化会被传递
c
a

(2, 6)

(3, 4)

array([[   0,    1,    2,    3, 1234,    5],
       [   6,    7,    8,    9,   10,   11]])

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

In [44]:
# 对ndarray进行切片会返回视图
s = a[:, 1:3]
s += 1000
a

array([[   0, 1001, 1002,    3],
       [1234, 1005, 1006,    7],
       [   8, 1009, 1010,   11]])

#### 2. 副本

In [47]:
# copy 方法对ndarray及数据进行完整复制
d = a.copy()
d

d.base is a.base

array([[   0, 1001, 1002,    3],
       [1234, 1005, 1006,    7],
       [   8, 1009, 1010,   11]])

False

### 六、其他操作
#### 1. np.unique()

In [62]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19]).reshape(2,-1)
a

# 注：调用np.unique时，如果多维ndarray没有指定axis，则会先展平
np.unique(a)  # 获取所有唯一值
np.unique(a, return_index=True)  # 获取所有唯一值及其索引
np.unique(a, return_counts=True)  # 获取所有唯一值及其重复的次数


array([[11, 11, 12, 13, 14, 15, 16],
       [17, 12, 13, 11, 14, 18, 19]])

array([11, 12, 13, 14, 15, 16, 17, 18, 19])

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([ 0,  2,  3,  4,  5,  6,  7, 12, 13], dtype=int64))

(array([11, 12, 13, 14, 15, 16, 17, 18, 19]),
 array([3, 2, 2, 2, 1, 1, 1, 1, 1], dtype=int64))

#### 2. np.flip()

In [64]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8])
a
np.flip(a)  # 反转一维ndarray

a = np.arange(12).reshape(3,4)
a
np.flip(a)  # 对二维ndarray，默认同时反转行和列
np.flip(a, axis=1)  # 也可以指定只反转行或列
np.flip(a, axis=0)

array([1, 2, 3, 4, 5, 6, 7, 8])

array([8, 7, 6, 5, 4, 3, 2, 1])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

array([[11, 10,  9,  8],
       [ 7,  6,  5,  4],
       [ 3,  2,  1,  0]])

array([[ 3,  2,  1,  0],
       [ 7,  6,  5,  4],
       [11, 10,  9,  8]])

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

### 七、保存和加载 ndarray 对象

In [70]:
a = np.array([1, 2, 3, 4, 5, 6])
np.save('filename', a)  # 保存为filename.npy文件
b = np.load('filename.npy')  # 加载